# Generated by Django 3.2 on 2021-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=122)),
                ('stream', models.CharField(max_length=122)),
                ('skills', models.CharField(max_length=122)),
                ('experience', models.CharField(max_length=122)),
                ('graduation', models.CharField(max_length=122)),
                ('about', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'studentregistration',
            },
        ),
    ]
