# Generated by Django 3.2 on 2021-05-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_registration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='studentregistration',
        ),
    ]
