# Generated by Django 3.2 on 2021-05-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_registration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='studentdetails',
        ),
    ]
