# Generated by Django 3.2 on 2021-05-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cdc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CDC',
        ),
    ]
