# Generated by Django 3.2 on 2021-05-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_registration_profile_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table=None,
        ),
    ]
