# Generated by Django 3.2 on 2021-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_registration_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='/images/civil.jpg', upload_to='profile_pictures'),
        ),
        migrations.AlterModelTable(
            name='registration',
            table='studentregistration',
        ),
    ]
