# Generated by Django 3.2 on 2021-05-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210522_1212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table=None,
        ),
    ]
