# Generated by Django 3.2 on 2021-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_registration_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='/images/civil.jpg', upload_to='pics'),
        ),
    ]
