# Generated by Django 3.2 on 2021-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
        migrations.AddField(
            model_name='registration',
            name='img',
            field=models.ImageField(default='images/gmit5.jpg', upload_to='profile_pics'),
        ),
    ]
