# Generated by Django 3.2 on 2021-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_registration_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='img',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
