# Generated by Django 3.2 on 2021-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_registration_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='img',
            field=models.ImageField(default='profile_pics/untitled-1.jpg', upload_to='profile_pics'),
        ),
    ]
