# Generated by Django 3.2 on 2021-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_registration_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=122)),
                ('image', models.ImageField(default='profile_pics/untitled-1.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
