# Generated by Django 3.2 on 2021-06-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='img',
        ),
    ]
