# Generated by Django 3.2 on 2021-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_auto_20210531_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='img',
        ),
    ]
