# Generated by Django 3.2 on 2021-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0005_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
